# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Anthony Anaedu
email: tony.anaedu@gmail.com
tagline: Developing Software Applications and providing IT Solutions to help businesses and individuals
description: Software Developer - IT Specialist - EE Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://anthonyanaedu.tk" # the base hostname & protocol for your site
paginate: 5
paginate_path: "blog/page:num"
twitter_username: aanaedu
github_username:  aanaedu
linkedin_username: tony.anaedu
googleplus_username: +AnthonyAnaeduDev
email_username: tony.anaedu@gmail.com
analytics_id: UA-77274083-1

collections:
  - projects
  
# Build settings
markdown: kramdown

# Permalinks
permalink: pretty

# Gems
gems:
  - jekyll-paginate
  - jekyll-sitemap
